---
- hosts: production
  user: root
  vars:
    username: root
    #password:    
    public_key: ~/.ssh/id_rsa.pub
  roles:
   - common
   - ufw
   - ssl
   - nginx
   - user

#   - haproxy
#   - mariadb

