---
- name: Check if sudo group is present
  group:
    name: sudo
    state: present


- name: Check if sudo group has privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"


- name: Create a passwordless sudo user
  user:
    name: sudo-user   
    group: sudo
    createhome: yes
    password: sudo-password
    shell: /bin/bash
    update_password: always
    state: present
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa


- name: Adding sudo-user to SSH allow list
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'AllowUsers sudo-user root' 

    
- name: Create a dedicated NGINX user
  user:
    name: nginx-user
    group: www-data
    createhome: yes
    password: nginx-password
    shell: /bin/bash
    update_password: always
    state: present
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa
    

- name: Removing NGINX user from the SSH allow list
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'DenyUsers nginx-user'


- name: Reload sshd configuration file
  service:
    name: sshd
    state: restarted

